[versions]
    agp = "9.0.0"
    kotlin = "2.2.20"
    coreKtx = "1.17.0"
    junit = "4.13.2"
    junitVersion = "1.3.0"
    espressoCore = "3.7.0"
    lifecycleRuntimeKtx = "2.9.4"
    activityCompose = "1.11.0"
    composeBom = "2025.10.00"
    composeMaterial3Android = "1.4.0"
    uiTooling = "1.9.3"
    material3 = "1.5.0-alpha08"
    material3AdaptiveNavigationSuite = "1.5.0-alpha11"
    litert = "2.0.2"
    navigationCompose = "2.9.5"
    retrofit = "3.0.0"
    vico = "2.2.1"
    appcompat = "1.7.1"
    core-splash-screen = "1.2.0"
    firebaseCrashlytics = "20.0.4"
    googleGmsGoogleServices = "4.4.4"
    googleFirebaseCrashlytics = "3.0.6"

[libraries]
    androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
    junit = { group = "junit", name = "junit", version.ref = "junit" }
    androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
    androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
    androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
    androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
    androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
    androidx-ui = { group = "androidx.compose.ui", name = "ui" }
    androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
    androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
    androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
    androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
    androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
    androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
    androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
    androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
    androidx-compose-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "composeMaterial3Android" }
    androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
    androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
    androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
    androidx-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "material3AdaptiveNavigationSuite" }
    litert = { group = "com.google.ai.edge.litert", name = "litert", version.ref = "litert" }
    retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
    retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
    vico-core = { group = "com.patrykandpatrick.vico", name = "core", version.ref = "vico" }
    vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
    vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }
    androidx-core-splash-screen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splash-screen"}
    firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }

[plugins]
    android-application = { id = "com.android.application", version.ref = "agp" }
    kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
    google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
    google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }